# Generated by Django 6.0.6 on 2026-07-16 01:39

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import events.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('banner', models.ImageField(blank=True, max_length=255, upload_to='events/banner/')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Publicado'), ('finished', 'Finalizado'), ('canceled', 'Cancelado')], default='draft', max_length=20)),
                ('slug', models.SlugField(validators=[django.core.validators.MinLengthValidator(limit_value=2), events.validators.validate_slug])),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug', 'organization'), name='unique_active_organization_and_slug'), models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='event_end_after_start')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
