# Generated by Django 6.0.6 on 2026-07-18 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('finished', 'Finalizado'), ('canceled', 'Cancelado')], default='draft', max_length=20),
        ),
    ]
