# Generated by Django 6.0.6 on 2026-07-26 23:25

import django.db.models.deletion
import django.db.models.manager
import events.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventmember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('manager', 'Gerente'), ('checkin_coordinator', 'Coordenador de check-in'), ('viewer', 'Visualizador')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceito'), ('revoked', 'Cancelado'), ('expired', 'Expirado')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField(default=events.models.expiration_date)),
                ('event', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='event_invites', to='events.event')),
                ('invited_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='sent_event_invites', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_event_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending'), ('deleted_at__isnull', True)), fields=('user', 'event'), name='unique_event_invite_pending')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
