# Generated by Django 6.0.6 on 2026-07-16 22:22

import django.core.validators
import organizations.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, validators=[django.core.validators.MinLengthValidator(limit_value=2), organizations.validators.validate_slug]),
        ),
        migrations.AlterField(
            model_name='organizationinvite',
            name='role',
            field=models.CharField(choices=[('owner', 'Dono'), ('manager', 'Gerente'), ('viewer', 'Visualizador'), ('checkin', 'Check-in'), ('coordenador_checkin', 'Coordenador de check-in')], max_length=32),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='role',
            field=models.CharField(choices=[('owner', 'Dono'), ('manager', 'Gerente'), ('viewer', 'Visualizador'), ('checkin', 'Check-in'), ('coordenador_checkin', 'Coordenador de check-in')], max_length=32),
        ),
    ]
