# Generated by Django 6.0.6 on 2026-07-18 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationinvite',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceito'), ('revoked', 'Cancelado'), ('expired', 'Expirado')], default='pending', max_length=20),
        ),
    ]
