# Generated by Django 6.0.6 on 2026-07-19 20:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organizationinvite_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='organizationfollow',
            name='unique_active_organization_follow',
        ),
        migrations.AddConstraint(
            model_name='organizationfollow',
            constraint=models.UniqueConstraint(fields=('user', 'organization'), name='unique_active_organization_follow'),
        ),
    ]
