# Generated by Django 6.0.6 on 2026-07-24 22:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_remove_organizationfollow_unique_active_organization_follow_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='organizationfollow',
            name='unique_active_organization_follow',
        ),
        migrations.AlterField(
            model_name='organizationinvite',
            name='role',
            field=models.CharField(choices=[('owner', 'Dono'), ('manager', 'Gerente'), ('viewer', 'Visualizador'), ('checkin_coordinator', 'Coordenador de check-in')], max_length=32),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='role',
            field=models.CharField(choices=[('owner', 'Dono'), ('manager', 'Gerente'), ('viewer', 'Visualizador'), ('checkin_coordinator', 'Coordenador de check-in')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='organizationfollow',
            constraint=models.UniqueConstraint(fields=('user', 'organization'), name='unique_organization_follow'),
        ),
    ]
