# Generated by Django 6.0.6 on 2026-08-03 00:34

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0004_eventinvite'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('quantity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30000)])),
                ('quantity_reserved', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30000)])),
                ('quantity_sold', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30000)])),
                ('min_quantity_per_order', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('max_quantity_per_order', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('max_quantity_per_user', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('sales_start_at', models.DateTimeField()),
                ('sales_end_at', models.DateTimeField()),
                ('absorb_fee', models.BooleanField(default=False)),
                ('event', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='events.event')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'constraints': [models.CheckConstraint(condition=models.Q(('sales_end_at__gt', models.F('sales_start_at'))), name='sales_end_after_start'), models.CheckConstraint(condition=models.Q(('max_quantity_per_order__gte', models.F('min_quantity_per_order'))), name='max_order_quantity_gte_min'), models.CheckConstraint(condition=models.Q(('quantity__gte', models.F('quantity_sold'))), name='quantity_gte_quantity_sold'), models.CheckConstraint(condition=models.Q(('quantity__gte', models.F('max_quantity_per_user'))), name='quantity_gte_max_quantity_per_user'), models.CheckConstraint(condition=models.Q(('quantity__gte', models.F('max_quantity_per_order'))), name='quantity_gte_max_quantity_per_order')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
